#!/usr/bin/env python3
"""Bundles the pure-Luau gameplay modules into a single standalone script that
the `luau` CLI can run outside Roblox, with Vector2/Color3 shimmed in.

Only modules with no Instance dependencies can be bundled: Config, Types,
Simulation, the level data and the AI. The renderer and the two entry scripts
are Roblox-only and are parse-checked instead."""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# (bundle name, source path) in dependency order.
MODULES = [
    ("Types", "src/Shared/Types.luau"),
    ("Config", "src/Shared/Config.luau"),
    ("Simulation", "src/Shared/Simulation.luau"),
    ("Crossroads", "src/Shared/Levels/Crossroads.luau"),
    ("AI", "src/Server/AI.luau"),
]

SHIM = r"""
-- === Roblox shim =========================================================
local Vector2 = {}
Vector2.__index = Vector2

function Vector2.new(x, y)
	return setmetatable({ X = x or 0, Y = y or 0 }, Vector2)
end

function Vector2.__add(a, b) return Vector2.new(a.X + b.X, a.Y + b.Y) end
function Vector2.__sub(a, b) return Vector2.new(a.X - b.X, a.Y - b.Y) end
function Vector2.__unm(a) return Vector2.new(-a.X, -a.Y) end
function Vector2.__eq(a, b) return a.X == b.X and a.Y == b.Y end

function Vector2.__mul(a, b)
	if type(a) == "number" then return Vector2.new(a * b.X, a * b.Y) end
	if type(b) == "number" then return Vector2.new(a.X * b, a.Y * b) end
	return Vector2.new(a.X * b.X, a.Y * b.Y)
end

function Vector2.__div(a, b)
	if type(b) == "number" then return Vector2.new(a.X / b, a.Y / b) end
	return Vector2.new(a.X / b.X, a.Y / b.Y)
end

function Vector2.Dot(self, other) return self.X * other.X + self.Y * other.Y end

Vector2.__index = function(self, key)
	if key == "Magnitude" then
		return math.sqrt(rawget(self, "X") ^ 2 + rawget(self, "Y") ^ 2)
	elseif key == "Unit" then
		local m = math.sqrt(rawget(self, "X") ^ 2 + rawget(self, "Y") ^ 2)
		return Vector2.new(rawget(self, "X") / m, rawget(self, "Y") / m)
	end
	return rawget(Vector2, key)
end

local Color3 = {}
function Color3.fromRGB(r, g, b) return { R = r / 255, G = g / 255, B = b / 255 } end
-- === end shim ============================================================
"""


def transform(source: str) -> str:
    # Requires are resolved to the already-bundled locals.
    source = re.sub(
        r'^local (\w+) = require\((?:ReplicatedStorage\.Shared|script)[\.\w]*\.(\w+)\)$',
        lambda m: f"local {m.group(1)} = __mod_{m.group(2)}",
        source,
        flags=re.M,
    )
    source = re.sub(r'^local \w+ = game:GetService\("[^"]+"\)$', "", source, flags=re.M)
    # `export type` is only legal at module scope; the bundle nests modules in
    # functions, and the runtime ignores type syntax either way.
    source = re.sub(r'^export type', "type", source, flags=re.M)
    return source


def main() -> int:
    out = ["-- GENERATED by tests/bundle.py -- do not edit", SHIM]

    for name, relative in MODULES:
        path = ROOT / relative
        out.append(f"local __mod_{name} = (function()\n{transform(path.read_text())}\nend)()\n")

    out.append("local Modules = {")
    out.extend(f"\t{name} = __mod_{name}," for name, _ in MODULES)
    out.append("}\n")

    out.append(transform((ROOT / "tests" / "simulation.spec.luau").read_text()))

    destination = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "tests" / "bundle.out.luau"
    destination.write_text("\n".join(out))
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
